endpoint: http://localhost:4466
datamodel: datamodel.prisma
generate:
  - generator: typescript-client
    output: config/prisma/prisma-client
hooks:
  post-deploy:
    - prisma generate -p config/prisma/prisma.development.yml
