endpoint: http://localhost:4466/graphql/test
datamodel: datamodel.prisma
generate:
  - generator: typescript-client
    output: config/prisma/prisma-client
hooks:
  post-deploy:
    - prisma generate -p config/prisma/prisma.test.yml
