version: "3.1"

services:
  db:
    image: postgres
    container_name: "postgres"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
    command: ["redis-server"]
